easy_admin:
  entities:
    Users:
      class:  App\Entity\Users

  design:
    brand_color: '#81b9ba'

  user:
    display_name: true
    display_avatar: true

  site_name: '<em style="font-size: 80%;"> DevCollab </em> Administrator Page'


