easy_admin:
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
    avatar_property_path: 'gravatar'
  site_name: '<em style="font-size: 80%;"> DevCollab Admin </em> '
  entities:
    Users:
      class:  App\Entity\Users
      label: 'Users'
      list:
        filters: ['name','last_name','town']
        title: "%%entity_label%% List"
        max_results: 20
        fields:
          - id
          - name
          - lastname
          - { property: 'email', type: 'email'}
          - town
          - { property: 'github_username',label: "GitHub" }
      form:
        fields:
          - { property: 'name', type: 'text', label: 'First Name', type_options: { required: true } }
          - { property: 'lastname', type: 'text', label: 'Last Name' }
          - { property: 'email', type: 'email', label: 'Email', type_options: { required: true } }
          - town
          - password
          - short_description
          - skills
    Skills:
      class:  App\Entity\Skills
      label: 'Skills'
      form:
        fields:
          - user_fk
          - skill_fk
      list:
        filters:
          - branch
        fields:
          - user_fk
          - skill_fk
    Teams:
      class: App\Entity\Teams
      label: 'Teams'
    Team:
      class: App\Entity\TeamPoints
      label: 'Team Points'
    Tasks:
      class: App\Entity\TeamTasks
      label: 'Team Tasks'
    Skill:
      class: App\Entity\Skill
      label: 'Skill'
      fields:
        - id
        - User fk
        - skill_fk
      list:
        filters: ['skill','branch']
  design:
    menu:
      - { label: 'Users'}
      - { entity: 'Users', css_class: 'menu--users', icon: 'user' }
      - { entity: 'Skills', css_class: 'menu--product text-bold', icon: 'book' }
      - { label: 'Teams'}
      - { entity: 'Teams', css_class: 'default', icon: 'group' }
      - { label: 'Admin'}
      - { entity: 'Skill', css_class: 'default', icon: 'cogs' }
    brand_color: 'rgba(71, 94, 55)'
    assets:
      favicon: '/assets/backend/dev-icon-8.png'
      css: ['css/easybundle.css']


